### ISSUE TITLE
`createURL` always returns root/empty url on first render

### ISSUE THREAD

**Issue by sixers** [algolia/instantsearch#5236]
## 🐛 Bug description

`createURL` produces incorrect URLs on the server (it's always root URL). 
The same applies to standard components from `react-instantsearch-hooks-web`: `Pagination`, etc.

## 🔍 Bug reproduction

**Steps to reproduce the behavior:**

1. Fork [[SSR example with Remix](https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/react-instantsearch-hooks/remix?file=/app/routes/index.tsx)
2. Edit `app/root.tsx` and comment out `<Scripts />`
3. Refresh the page and inspect the `href`s of pagination links (`.ais-Pagination-link`)

**Live reproduction:**

https://codesandbox.io/s/zen-cache-7cyfjo?file=/app/root.tsx

## 💭 Expected behavior

`createURL` should produce correct URLs when server rendering, without running any code on the client.

## Environment

- React InstantSearch Hooks version: 6.38.1
- React version: 17.0.2
- Browser: Chrome
- OS: MacOS

**Comment by Haroenv** [comment]
This is a complicated edge case, a bit of a chicken-and-egg problem.

1. createURL called by the widget is createURL called by the connector
2. the result of createURL depends on what the current UI state + mounted widgets is
3. when you call createURL, in an initial render (like on server side rendering) the widgets aren't yet mounted

This problem also happens when you aren't doing server side rendering, but as the second render is right after the first one, it never commits the incomplete URL.

At this point I'm not yet sure what the solution would be.

**Comment by DB-Alex** [comment]
I have the same problem.

**Comment by DB-Alex** [comment]
Still present in 6.39.2

**Comment by Haroenv** [comment]
Yes, we have not found a method to solve this problem yet.

**Comment by DB-Alex** [comment]
@Haroenv any update on this?

**Comment by Haroenv** [comment]
Unfortunately not. A workaround could be to add all widgets that have an effect to the URL early "virtualised", like this:

```jsx
const VirtualPagination = (props) => { usePagination(props) }

const App = () => (
  <InstantSearch>
    <VirtualPagination />
    <Pagination />
  </InstantSearch>
)
```

**Comment by DB-Alex** [comment]
Hi @Haroenv we have that already but the SSR code contains empty links on pagination until page becomes active.

**Comment by avremel** [comment]
@Haroenv 

We are using NextJS with SSR and ran into this issue when implementing `useRefinementList`. To improve our SEO, we want to render links for each filter (but default to client side navigation once JS loads). We are blocked because `createURL` only runs on the client.

> This is a complicated edge case, a bit of a chicken-and-egg problem.
> 
> 1. createURL called by the widget is createURL called by the connector
> 2. the result of createURL depends on what the current UI state + mounted widgets is
> 3. when you call createURL, in an initial render (like on server side rendering) the widgets aren't yet mounted

Is this actually a limitation when running `InstantSearchSSRProvider` ([docs](https://www.algolia.com/doc/api-reference/widgets/ssr-provider/react-hooks/))?

I'm running `getServerState` ([docs](https://www.algolia.com/doc/api-reference/widgets/server-state/react-hooks/)) in `getServerSideProps` _before_ SSR begins. At this point, we don't care if `createURL` returns nothing. At the next stage, we begin SSR knowing the UI state. Why can't `createURL` know the correct URL?

**Comment by aymeric-giraudet** [comment]
Hi everyone ! 👋

This is being addressed right now.
A fix should be released either next week or the one after.

Thank you for your patience ☺️

**Comment by DB-Alex** [comment]
@Haroenv createURL from the usePagination hook is not starting at 0 but at 1.

For example:

```
const { canRefine, pages, refine } = usePagination(props);

createURL(0) => Gives another url as refine(0)
createURL(1) => Gives another url as refine(1)

```

**Comment by Haroenv** [comment]
Just opened https://github.com/algolia/instantsearch/issues/5797 to deal with this, thanks @DB-Alex
