### ISSUE TITLE
<Configure /> with react-instantsearch-hooks-router-nextjs triggers double onStateChange

### ISSUE THREAD

**Issue by LefanTan** [algolia/instantsearch#5481]
### 🐛 Current behavior

When there's a <Configure /> component being used, making updates to any of the algolia states causes onStateChange to be called twice. Once with the configure object, second time without. 

First console log of `uiState`:

```
{
instant_search: Object
      configure: Object
           hitsPerPage: 30
      query: "12"
}

```

Second console log of `uiState`:

```
{
instant_search: Object
      query: "12"
}
```

### 🔍 Steps to reproduce

1. Add <Configure /> as a children under <InstantSearch />. Add any configuration to <Configure />, in my case I used `hitsPerPage`
2. Add custom `onStateChange` handler. Add a console log to observe `uiState`.
3. Trigger `onStateChange` by making updates to any of the algolia components (Hierarchical Menu, etc)
4. Observe the two console logs being printed.

### Live reproduction

https://codesandbox.io/s/epic-euler-k14dg9?file=/pages/index.tsx:2035-2048

### 💭 Expected behavior

`onStateChange` should only be called once, and always with configure object. The extra state change is causing unexpected re-renders throughout the application. Thank you.

### Package version

react-instantsearch-hooks-router-nextjs: 6.40.0, react-instantsearch-hooks-web: 6.38.3, react-instantsearch-hooks-server: 6.39.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aymeric-giraudet** [comment]
Hi @LefanTan, thanks for raising this issue and providing a CodeSandbox for it !

Indeed this is something we have overlooked, `Configure` does not persist in the URL. However calling `setUiState` without it doesn't seem to override the `SearchParameters` so it doesn't trigger any new network request nor a re-render.

What's causing the re-render is actually the push action with the Next.js router, here's a screenshot of React DevTools profiler on the CodeSandbox you sent : 
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/9158954/219392359-5157b024-084f-4cd9-b2e0-1f08d07dd714.png">

There are 5 renders when clicking on a refinement list item : 
1. Upon clicking on the refinement list item, it is re-rendered to show that it's checked
2. After receiving results from Algolia, we update the UI accordingly
3. Seems to be re-rendering Next.js links before the route push ?
4. Route has changed, `hydrateRoot`  is called and re-renders the whole page
5. `RouteAnnouncer` gets re-rerendered

You can notice that even if `setUiState` is called twice, it actually doesn't trigger a render the second time, it's the Next router that does.

This is more of a drawback from having to use Next.js router in order to have functioning `popState` actions. I think there are ways to push Next.js compatible state without triggering a re-render of the whole page, but I wouldn't recommend it as it's not future-proof.
I think the second render is fine as it's done in a debounced manner after the user has totally typed their query, and it's done when they would normally look at the results.

Now I'm aware this creates unnecessary noise when using a custom `onStateChange`, so I'll still look for a fix for that (I think if we call `setUiState` only when the push wasn't from InstantSearch should do the trick), but be aware that this won't change the fact that a whole re-render is done when the URL changes.

**Comment by pixelkoduje** [comment]
I have the same - it performs 3 queries with each click, which causes jumps and shows different query execution times many times.

**Comment by LefanTan** [comment]
@aymeric-giraudet Thanks a lot!
