### ISSUE TITLE
react-instantsearch-nextjs pagination doesnt move to top

### ISSUE THREAD

**Issue by web-programmer-here** [algolia/instantsearch#5930]
### 🐛 Current behavior

Using `react-instantsearch-nextjs` with pagination, when you go to next or prev pages, the element doesnt scroll to the top and remains in same spot. 

### 🔍 Steps to reproduce

1. Install react-instantsearch-nextjs
2. Pass `routing`
3. Add `<Pagination>`
4. Click on page numbers

### Live reproduction

NA

### 💭 Expected behavior

Maybe go to the top of the search element?

### Package version

react-instantsearch-nextjs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aymeric-giraudet** [comment]
Hey @web-programmer-here 

We removed it because it was inconsistent with the rest of the library, we never set scroll up anywhere, you can check it for yourself with this simple React InstantSearch app : https://codesandbox.io/s/github/algolia/instantsearch/tree/templates/react-instantsearch
So this always was the expected behavior.

You can however implement it yourself on a widget basis : 
```jsx
<Pagination 
  onClick={() => {
    scrollTo(0, 0);
  }
/>
```
